spring:
  application:
    name: room
  data:
    mongodb:
      uri: ${mongo-connection-uri}
      database: ${db-name}

server:
  port: 8000

user:
  secretKey: ${secret-key}
  token:
    expiry:
      time: ${jwt-token-expiry}